### PR TITLE
sets step title as h2 instead of div

### LINKED ISSUE #37: Step titles in step-by-step navigation block should not use div
I think the step titles in the navigation block should use a heading tag for semantics and screenreaders.

Judging by our default markup, I think `h2` should probably be used.

### PR DESCRIPTION
**Pull request by markconroy**
Closes #37

### CODE REVIEW

**Comment by ekes** [comment]
Does replace `<div>` with `<h2>` on list in on both landing page and individual step pages. Can't see it falling out of h1 / h2 / h3 structure in any bad way. So works.

Is this something we want to push to existing sites? I'm guessing it is?

**Comment by finnlewis** [comment]
Discussing with @ekes and @markconroy in our Merge Monday call, we'd like to add an update hook to change the view to render h2s rather than divs. 

The update hook can load the view, update the element to h2, save the view. 

Release notes warning of this change will also be provided. 

@ekes will give this a bash!

**Comment by ekes** [comment]
Who wants to double check that @finnlewis ?

**Review by finnlewis — APPROVED** [review]
Yeah, this works nicely. Thanks @markconroy  and @ekes !!!

**Pull request merged**
