### PR TITLE
Standardised field order on node edit page

### LINKED ISSUE #74: Standardise field order
Spun out of https://github.com/localgovdrupal/localgov/issues/487

For step-by-step:

- the "step by step overview" field should be first and a lookup type, not drop down menu
- the field should be labelled "parent page"
- it's type should be a lookup not a drop down menu

### PR DESCRIPTION
**Pull request by stephen-cox**
Fixes #74

### CODE REVIEW

**Comment by stephen-cox** [comment]
Step by step page edit form now looks like

image

**Comment by willguv** [comment]
Nice one @stephen-cox - is it easy to remove the "edit summary" link from the body field label? Kind of redundant now

**Review by finnlewis — APPROVED** [review]
Tested locally with demo content, all looks to do what it says on the tin.
Thanks @stephen-cox !

**Comment by stephen-cox** [comment]
> is it easy to remove the "edit summary" link from the body field label

Like on guide pages, the summary is used in the teaser view. I'm not sure this view mode is used anywhere, but it's generally expected to exist in Drupal, so getting rid of it would require further discussion.

**Pull request merged**
