### PR TITLE
Update overview teaser view mode to only include summary

### LINKED ISSUE #32: Fix teaser display mode for Step-by-step overviews
Currently includes fields other than summary, shown on Service landing page with child step-by-step overview:

image

### PR DESCRIPTION
**Pull request by danchamp**
Closes #32:

- Only includes the summary field in teasers, fixing the presentation of service landing pages with step-by-step children.

### CODE REVIEW

**Comment by danchamp** [comment]
@stephen-cox @ekes Any pointers as to why these tests are failing, and how to fix them?

image

**Comment by stephen-cox** [comment]
@danchamp Tests should be fixed with #34. Feel free to merge the `hotfix/fix-github-ci-for-2.0.0` branch into yours to get the tests running.

**Comment by danchamp** [comment]
Thanks @stephen-cox, that fixed it.

**Review by finnlewis — APPROVED** [review]
This works for me. Fresh install sets the teaser display as described, which looks to be a more reasonable default.

**Pull request merged**
